config/routes.rb
Rails.application.routes.draw do
  root to: 'users#index'

  # main index page
  get 'users/index' => 'users#index', as: 'usersindex'

  get 'users/show' => 'users#show', as: 'usersshow'


  get 'products/index' => 'products#index', as: "productsindex"

  get 'products/new' => 'products#new', as: "productsnew"

  get 'products/show/:id' => 'products#show', as: "productsshow"

  get 'products/:id/edit' => 'products#edit', as: "productsedit"

  post 'products/create' => 'products#create', as: "productscreate"

  patch 'products/:id/update' => 'products#update', as: "productsupdate"

  delete 'products/:id/destroy' => 'products#destroy', as: "productsdestroy"



  get 'sales/index' => 'sales#index', as: "salesindex"

  get 'sales/new' => 'sales#new', as: "salesnew"

  get 'sales/show/:id' => 'sales#show', as: "salesshow"

  get 'sales/:id/edit' => 'sales#edit', as: "salesedit"

  post 'sales/create' => 'sales#create', as: "salescreate"

  patch 'sales/:id/update' => 'sales#update', as: "salesupdate"

  delete 'sales/:id/destroy' => 'sales#destroy', as: "salesdestroy"



  get 'markets/index' => 'markets#index', as: "marketsindex"

  get 'markets/show/:id' => 'markets#show', as: "marketsshow"

  get 'markets/:state/show' => 'markets#showstate', as: "marketsshowstate"

  get 'markets/:id/edit' => 'markets#edit', as: "marketsedit"

  get 'markets/new' => 'markets#new', as: "marketsnew"

  post 'markets/create' => 'markets#create', as: "marketscreate"

  patch 'markets/:id/update' => 'markets#update', as: "marketsupdate"

  delete 'markets/:id/destroy' => 'markets#destroy', as: "marketsdestroy"



  get 'vendors/index' => 'vendors#index', as: "vendorsindex"

  get 'vendors/new' => 'vendors#new', as: "vendorsnew"

  get 'vendors/show/:id' => 'vendors#show', as: "vendorsshow"

  get 'vendors/:id/edit' => 'vendors#edit', as: "vendorsedit"

  post 'vendors/create' => 'vendors#create', as: "vendorscreate"

  patch 'vendors/:id/update' => 'vendors#update', as: "vendorsupdate"

  delete 'vendors/:id/destroy' => 'vendors#destroy', as: "vendorsdestroy"

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index

  end

  def show

  end
end

app/helpers/users_helper.rb
module UsersHelper
  def us_states
     [
       ['Alabama', 'Alabama'],
       ['Alaska', 'Alaska'],
       ['Arizona', 'Arizona'],
       ['Arkansas', 'Arkansas'],
       ['California', 'California'],
       ['Colorado', 'Colorado'],
       ['Connecticut', 'Connecticut'],
       ['Delaware', 'Delaware'],
       ['District of Columbia','District of Columbia'],
       ['Florida', 'Florida'],
       ['Georgia', 'Georgia'],
       ['Hawaii', 'Hawaii'],
       ['Idaho', 'Idaho'],
       ['Illinois', 'Illinois'],
       ['Indiana', 'Indiana'],
       ['Iowa', 'Iowa'],
       ['Kansas', 'Kansas'],
       ['Kentucky', 'Kentucky'],
       ['Louisiana', 'Louisiana'],
       ['Maine', 'Maine'],
       ['Maryland', 'Maryland'],
       ['Massachusetts', 'Massachusetts'],
       ['Michigan', 'Michigan'],
       ['Minnesota', 'Minnesota'],
       ['Mississippi', 'Mississippi'],
       ['Missouri', 'Missouri'],
       ['Montana', 'Montana'],
       ['Nebraska', 'Nebraska'],
       ['Nevada', 'Nevada'],
       ['New Hampshire', 'New Hampshire'],
       ['New Jersey', 'New Jersey'],
       ['New Mexico', 'New Mexico'],
       ['New York', 'New York'],
       ['North Carolina', 'North Carolina'],
       ['North Dakota', 'North Dakota'],
       ['Ohio', 'Ohio'],
       ['Oklahoma', 'Oklahoma'],
       ['Oregon', 'Oregon'],
       ['Pennsylvania', 'Pennsylvania'],
       ['Puerto Rico', 'Puerto Rico'],
       ['Rhode Island', 'Rhode Island'],
       ['South Carolina', 'South Carolina'],
       ['South Dakota', 'South Dakota'],
       ['Tennessee', 'Tennessee'],
       ['Texas', 'Texas'],
       ['Utah', 'Utah'],
       ['Vermont', 'Vermont'],
       ['Virginia', 'Virginia'],
       ['Washington', "Washington"],
       ['West Virginia', 'West Virginia'],
       ['Wisconsin', 'Wisconsin'],
       ['Wyoming', 'Wyoming']
     ]
 end
end

app/views/users/index.html.erb
<h1 id="center">I am a...</h1>

<section class="image-format">

  <div>
    <%= link_to(image_tag("users.png", :alt => "user", :title => "User"), "users/show") %>
    <h3>Visitor</h3>
  </div>
  <div>
    <%= link_to(image_tag("market-stall.jpg", :alt => "market", :title => "Market"), "markets/index") %>
    <h3>Market</h3>
  </div>
  <div>
    <%= link_to(image_tag("vendoroption.png", :alt => "vendor", :title => "Vendor"), "vendors/index") %>
    <h3>Vendor</h3>
  </div>

</section>

app/views/users/show.html.erb
<h1>Welcome Visitor!</h1>
<h3><%= link_to("See all Markets", marketsindex_path) %></h3>
<p>or select a market:
  <%= collection_select :market_id, :name, Market.order(:name),:id,:name, include_blank: false %> **this dropdown doesn't work yet**
  <%= button_to 'Go', marketsshow_path(:id), method: :get, class: :button %></p>

<p>See Market by State:
  <%= select_tag :state, options_for_select( us_states ) %> **this dropdown doesn't work yet, to filter by state change code. Currently set to WA**
  <%= button_to 'Go', marketsshowstate_path('Florida'), method: :get, class: :button %>
</p>



<h3><%= link_to("See all Vendors", vendorsindex_path) %></h3>
<p>or select a vendor:
  <%= collection_select :vendor_id, :name, Vendor.order(:name),:id,:name, include_blank: false %>**this dropdown doesn't work yet**
  <%= button_to 'Go', vendorsshow_path(:id), method: :get, class: :button %></p>


<h3><%= link_to("See all Products", productsindex_path) %></h3>
<p>or select a product to see where it is sold:
  <%= collection_select :product_id, :name, Product.order(:name),:id,:name, include_blank: false %>**this dropdown doesn't work yet**
  <%= button_to 'Go', productsshow_path(:id), method: :get, class: :button %></p>