config/routes.rb
Rails.application.routes.draw do
  root to: 'users#index'

  # main index page
  get 'users/index' => 'users#index', as: 'usersindex'

  get 'users/show' => 'users#show', as: 'usersshow'


  get 'products/index' => 'products#index', as: "productsindex"

  get 'products/new' => 'products#new', as: "productsnew"

  get 'products/show/:id' => 'products#show', as: "productsshow"

  get 'products/:id/edit' => 'products#edit', as: "productsedit"

  post 'products/create' => 'products#create', as: "productscreate"

  patch 'products/:id/update' => 'products#update', as: "productsupdate"

  delete 'products/:id/destroy' => 'products#destroy', as: "productsdestroy"



  get 'sales/index' => 'sales#index', as: "salesindex"

  get 'sales/new' => 'sales#new', as: "salesnew"

  get 'sales/show/:id' => 'sales#show', as: "salesshow"

  get 'sales/:id/edit' => 'sales#edit', as: "salesedit"

  post 'sales/create' => 'sales#create', as: "salescreate"

  patch 'sales/:id/update' => 'sales#update', as: "salesupdate"

  delete 'sales/:id/destroy' => 'sales#destroy', as: "salesdestroy"



  get 'markets/index' => 'markets#index', as: "marketsindex"

  get 'markets/show/:id' => 'markets#show', as: "marketsshow"

  get 'markets/:state/show' => 'markets#showstate', as: "marketsshowstate"

  get 'markets/:id/edit' => 'markets#edit', as: "marketsedit"

  get 'markets/new' => 'markets#new', as: "marketsnew"

  post 'markets/create' => 'markets#create', as: "marketscreate"

  patch 'markets/:id/update' => 'markets#update', as: "marketsupdate"

  delete 'markets/:id/destroy' => 'markets#destroy', as: "marketsdestroy"



  get 'vendors/index' => 'vendors#index', as: "vendorsindex"

  get 'vendors/new' => 'vendors#new', as: "vendorsnew"

  get 'vendors/show/:id' => 'vendors#show', as: "vendorsshow"

  get 'vendors/:id/edit' => 'vendors#edit', as: "vendorsedit"

  post 'vendors/create' => 'vendors#create', as: "vendorscreate"

  patch 'vendors/:id/update' => 'vendors#update', as: "vendorsupdate"

  delete 'vendors/:id/destroy' => 'vendors#destroy', as: "vendorsdestroy"

end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
  belongs_to :market
  has_many :products
  has_many :sales

  validates :name, presence: true, uniqueness: true
  validates :employees, :market_id, presence: true, numericality: { only_integer: true }

end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController

  def findVendor
    return Vendor.find(params[:id].to_i)
  end

  def index
    @vendors = Vendor.all
  end

  def new
    @vendor = Vendor.new
  end

  def show
    @vendor = findVendor
  end

  def edit
    @vendor = findVendor

    if @vendor == nil
          render :file => 'public/404.html',
              :status => :not_found
    end
  end

  def update
    @vendor = findVendor

    if @vendor == nil
          render :file => 'public/404.html',
              :status => :not_found
    end

    if @vendor.update(name: params[:vendor][:name], employees: params[:vendor][:employees], market_id: params[:vendor][:market_id])
      redirect_to action: "show"
    else
      render 'edit'
    end
  end

  def create
    @params = params
    @vendor = Vendor.new
    @vendor.name = params[:vendor][:name]
    @vendor.employees = params[:vendor][:employees]
    @vendor.market_id = params[:vendor][:market_id]

    if(@vendor.save)
        # Saved successfully; go to the index
        redirect_to :action => "index"
    else
        # Validation failed; show the "new" form again...
        render :action => :new
    end
  end

  def destroy
    @vendor = findVendor
    @vendor.destroy

    redirect_to action: "index"
  end
  # 
  # def total_sales
  #   @vendor = findVendor
  #   totalsales = 0.0
  #
  #   if @vendor.sales == nil
  #     return totalsales
  #   else
  #     @vendor.sales.each do |sale|
  #       totalsales += sale.amount / 100.0
  #     end
  #   end
  #
  #   return totalsales
  # end

end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/vendors/_vendorform.html.erb
<%= form_for @vendor,
  url: action_name do |f| %>
<ul>
  <li><%= f.label :name %></li>
  <li><%= f.text_field :name %></li>

  <li><%= f.label :employees %></li>
  <li><%= f.text_field :employees %></li>

  <li><%= f.label :market_id %></li>
  <li><%= f.select(:market_id, Market.all.map{|u| [u.name, u.id]}, {include_blank: true}) %></li>

  <li><%= f.submit class: 'button' %>
</ul>

  <% end %>

app/views/vendors/create.html.erb
<h1>Vendors#create</h1>
<p>Find me in app/views/vendors/create.html.erb</p>

app/views/vendors/destroy.html.erb
<h1>Vendors#destroy</h1>
<p>Find me in app/views/vendors/destroy.html.erb</p>

app/views/vendors/edit.html.erb
<h1>Edit a Vendor</h1>
<%= render partial: "vendorform", locals: { action_name: "update", params: {id: @vendor.id }} %>

app/views/vendors/index.html.erb
<h1>Here are all of the vendors!</h1>
<% @vendors.each do |vendor| %>

  <article>
    <h2><%= link_to(vendor.name, vendorsshow_path(vendor.id)) %></h2>
  </article>

<% end %>

app/views/vendors/new.html.erb
<h1>Add a Vendor</h1>
<%= render partial: "vendorform", locals: { action_name: "create" } %>

app/views/vendors/show.html.erb
<h1><%= @vendor[:name] %></h1>
<ul class="align-buttons">
  <li><%= button_to 'Delete this Vendor', vendorsdestroy_path(params[:id]), :class => "button", method: :delete, data: {confirm: 'Are you sure you want to delete this vendor?'} %></li>
</ul>
<p>Current employees: <%= @vendor[:employees] %></p>
Products sold:
<ul>
  <% @vendor.products.each do |product| %>
  <li><%= link_to(product.name, productsshow_path(product.id)) %></li>
  <% end %>
</ul>
<ul class="align-buttons">
  <li><%= button_to 'New Product', productsnew_path(), :class => "button", method: :get %></li>
</ul>


<article>
  <h3> Currently at:  </h3>
  <p><%= link_to(@vendor.market.name, marketsshow_path(@vendor.market.id)) %></p>
  <p><%= @vendor.market.address %></p>
  <p><%= @vendor.market.city %>, <%= @vendor.market.state %> <%= @vendor.market.zip %></p>
  <p>County: <%= @vendor.market.county %></p>
</article>

<article>
  <h3>This Month's Sales:</h3>
  <ul>
    <% if @vendor.sales != nil %>
      <% totalsales = 0.0 %>
      <% @vendor.sales.each do |sale| %>
        <% if sale.purchase_time.to_time.month == 10 %>
          <% sale_with_decimals = sale.amount / 100.0 %>
            <li><%= link_to(sale.product.name, salesshow_path(sale.id)) %>: $<%= (sprintf "%.2f", sale_with_decimals) %>, <%= sale.purchase_time.to_datetime.month %>/<%= sale.purchase_time.to_datetime.year %></li>
            <% totalsales += sale_with_decimals %>
            <% end %>
        <% end %>
      <p>Total Sales this Month: $<%= (sprintf "%.2f", totalsales) %></p>
    <% end %>
  </ul>

  <h3>All Sales:</h3>
  <ul>

    <% if @vendor.sales != nil %>
      <% totalsales = 0.0 %>

      <% @vendor.sales.each do |sale| %>
        <% sale_with_decimals = sale.amount / 100.0 %>
          <li><%= link_to(sale.product.name, salesshow_path(sale.id)) %>: $<%= (sprintf "%.2f", sale_with_decimals) %>
          <% totalsales += sale_with_decimals %>, <%= sale.purchase_time.to_datetime.month %>/<%= sale.purchase_time.to_datetime.year %></li>
      <% end %>
      <p>Total Sales: $<%= (sprintf "%.2f", totalsales) %></p>

    <% else %>
      <h3>You might want to try selling something.</h3>
    <% end %>
  </ul>
  <ul class="align-buttons">
    <li><%= button_to 'New Sale', salesnew_path(), :class => "button", method: :get %></li>
  </ul>

</article>

app/views/vendors/update.html.erb
<h1>Vendors#update</h1>
<p>Find me in app/views/vendors/update.html.erb</p>