config/routes.rb
Rails.application.routes.draw do
  root to: 'users#index'

  # main index page
  get 'users/index' => 'users#index', as: 'usersindex'

  get 'users/show' => 'users#show', as: 'usersshow'


  get 'products/index' => 'products#index', as: "productsindex"

  get 'products/new' => 'products#new', as: "productsnew"

  get 'products/show/:id' => 'products#show', as: "productsshow"

  get 'products/:id/edit' => 'products#edit', as: "productsedit"

  post 'products/create' => 'products#create', as: "productscreate"

  patch 'products/:id/update' => 'products#update', as: "productsupdate"

  delete 'products/:id/destroy' => 'products#destroy', as: "productsdestroy"



  get 'sales/index' => 'sales#index', as: "salesindex"

  get 'sales/new' => 'sales#new', as: "salesnew"

  get 'sales/show/:id' => 'sales#show', as: "salesshow"

  get 'sales/:id/edit' => 'sales#edit', as: "salesedit"

  post 'sales/create' => 'sales#create', as: "salescreate"

  patch 'sales/:id/update' => 'sales#update', as: "salesupdate"

  delete 'sales/:id/destroy' => 'sales#destroy', as: "salesdestroy"



  get 'markets/index' => 'markets#index', as: "marketsindex"

  get 'markets/show/:id' => 'markets#show', as: "marketsshow"

  get 'markets/:state/show' => 'markets#showstate', as: "marketsshowstate"

  get 'markets/:id/edit' => 'markets#edit', as: "marketsedit"

  get 'markets/new' => 'markets#new', as: "marketsnew"

  post 'markets/create' => 'markets#create', as: "marketscreate"

  patch 'markets/:id/update' => 'markets#update', as: "marketsupdate"

  delete 'markets/:id/destroy' => 'markets#destroy', as: "marketsdestroy"



  get 'vendors/index' => 'vendors#index', as: "vendorsindex"

  get 'vendors/new' => 'vendors#new', as: "vendorsnew"

  get 'vendors/show/:id' => 'vendors#show', as: "vendorsshow"

  get 'vendors/:id/edit' => 'vendors#edit', as: "vendorsedit"

  post 'vendors/create' => 'vendors#create', as: "vendorscreate"

  patch 'vendors/:id/update' => 'vendors#update', as: "vendorsupdate"

  delete 'vendors/:id/destroy' => 'vendors#destroy', as: "vendorsdestroy"

end

app/models/market.rb
class Market < ActiveRecord::Base
  has_many :vendors
  has_many :products
  has_many :sales

  validates :name, presence: true, uniqueness: true
  validates :address, :city, :state, :county, presence: true
  validates :zip, presence: true, numericality: { only_integer: true }

end

app/controllers/markets_controller.rb
class MarketsController < ApplicationController

  def findMarket
    return Market.find(params[:id].to_i)
  end

  def index
    @markets = Market.all
  end

  def new
    @market = Market.new
  end

  def create
    @params = params
    @market = Market.new
    @market.name = params[:market][:name]
    @market.address = params[:market][:address]
    @market.city = params[:market][:city]
    @market.state = params[:market][:state]
    @market.zip = params[:market][:zip]
    @market.county = params[:market][:county]

    if(@market.save)
        # Saved successfully; go to the index
        redirect_to :action => "index"
    else
        # Validation failed; show the "new" form again...
        render :action => :new
    end

  end

  def show
    @market = findMarket
  end

  def showstate
    @markets = Market.where( state: params[:state] )
    if @markets == nil
      redirect_to action: 'marketsindex'
    end
  end

  def edit
    @market = findMarket

    if @market == nil
      render :file => 'public/404.html',
          :status => :not_found
    end

  end

  def update
    @market = findMarket

    if @market == nil
          render :file => 'public/404.html',
              :status => :not_found
    end

    if @market.update(name: params[:market][:name], address: params[:market][:address], city: params[:market][:city], state: params[:market][:state], zip: params[:market][:zip], county: params[:market][:county])
      redirect_to action: "show"
    else
      render 'edit'
    end
  end


  def destroy
    @market = findMarket
    @market.destroy

    redirect_to action: "index"
  end
end

app/helpers/markets_helper.rb
module MarketsHelper
end

app/views/markets/_marketform.html.erb
<%= form_for @market,
  url: action_name do |f| %>
<ul>
  <li><%= f.label :name %></li>
  <li><%= f.text_field :name %></li>

  <li><%= f.label :address %></li>
  <li><%= f.text_field :address %></li>

  <li><%= f.label :city %></li>
  <li><%= f.text_field :city %></li>

  <li><%= f.label :state %></li>
  <li><%= f.text_field :state %></li>

  <li><%= f.label :zip %></li>
  <li><%= f.text_field :zip %></li>

  <li><%= f.label :county %></li>
  <li><%= f.text_field :county %></li>

  <li><%= f.submit class: 'button' %></li>
</ul>

  <% end %>

app/views/markets/create.html.erb
<h1>Markets#create</h1>
<p>Find me in app/views/markets/create.html.erb</p>

app/views/markets/destroy.html.erb
<h1>Markets#destroy</h1>
<p>Find me in app/views/markets/destroy.html.erb</p>

app/views/markets/edit.html.erb
<h1>Edit a Market</h1>
<%= render partial: "marketform", locals: { action_name: "update", params: {id: @market.id }} %>

app/views/markets/index.html.erb
<h1>Here are all of the markets!</h1>
<% @markets.each do |market| %>

  <article>
    <h2><%= link_to(market.name, marketsshow_path(market.id)) %></h2>
  </article>

<% end %>

app/views/markets/new.html.erb
<h1>Add Your Market</h1>
<%= render partial: "marketform", locals: { action_name: "create" } %>

app/views/markets/show.html.erb
<h1><%= @market[:name] %></h1>
<article>
  <h3>Located at: </h3>
  <p><%= @market.address %></p>
  <p><%= @market.city %>, <%= @market.state %> <%= @market.zip %></p>
  <p>County: <%= @market.county %></p>
</article>

<article>
  <h3> Current vendors:  </h3>
  <% @market.vendors.each do |vendor| %>
    <p><%= link_to(vendor.name, vendorsshow_path(vendor.id)) %></p>
  <% end %>
</article>

<article>
  <h3> Current products:  </h3>
  <% @market.vendors.each do |vendor| %>
        <% vendor.products.each do |product| %>
          <p><%= link_to(product.name, productsshow_path(product.id)) %></p>
      <% end %>
  <% end %>
</article>

<article>
  <h3>This Month's Sales:</h3>
  <ul>
    <% totalsales = 0.0 %>
    <% @market.vendors.each do |vendor| %>
      <% vendor.sales.each do |sale| %>
        <% if sale.purchase_time.to_time.month == 10 %>
          <% sale_with_decimals = sale.amount / 100.0 %>
            <li><%= link_to(sale.product.name, salesshow_path(sale.id)) %>: $<%= (sprintf "%.2f", sale_with_decimals) %>, <%= sale.purchase_time.to_datetime.month %>/<%= sale.purchase_time.to_datetime.year %></li>
            <% totalsales += sale_with_decimals %>
            <% end %>
          <% end %>
        <% end %>
    <p>Total Sales this Month: $<%= (sprintf "%.2f", totalsales) %></p>
  </ul>
</article>

<ul class="align-buttons">
  <li><%= button_to 'Add New Vendor', vendorsnew_path(params[:id]), :class => "button", method: :get %></li>
  <li><%= button_to 'Edit Market Info', marketsedit_path(params[:id]), :class => "button", method: :get %></li>
  <li><%= button_to 'Delete Market', marketsdestroy_path(params[:id]), :class => "button", method: :delete, data: {confirm: 'Are you sure?'} %>
  </li>
</ul>

app/views/markets/showstate.html.erb
<% if @markets.count == 0 %>
  <h1>Sorry, there are no Farmers Markets in that state.</h1>
<% else %>
  <h1>Here are all of the markets in <%= @markets.first.state %>!</h1>
  <% @markets.each do |market| %>

    <article>
      <h2><%= link_to(market.name, marketsshow_path(market.id)) %></h2>
    </article>

  <% end %>
<% end %>

app/views/markets/update.html.erb
<h1>Markets#update</h1>
<p>Find me in app/views/markets/update.html.erb</p>