config/routes.rb
Rails.application.routes.draw do
  root to: 'users#index'

  # main index page
  get 'users/index' => 'users#index', as: 'usersindex'

  get 'users/show' => 'users#show', as: 'usersshow'


  get 'products/index' => 'products#index', as: "productsindex"

  get 'products/new' => 'products#new', as: "productsnew"

  get 'products/show/:id' => 'products#show', as: "productsshow"

  get 'products/:id/edit' => 'products#edit', as: "productsedit"

  post 'products/create' => 'products#create', as: "productscreate"

  patch 'products/:id/update' => 'products#update', as: "productsupdate"

  delete 'products/:id/destroy' => 'products#destroy', as: "productsdestroy"



  get 'sales/index' => 'sales#index', as: "salesindex"

  get 'sales/new' => 'sales#new', as: "salesnew"

  get 'sales/show/:id' => 'sales#show', as: "salesshow"

  get 'sales/:id/edit' => 'sales#edit', as: "salesedit"

  post 'sales/create' => 'sales#create', as: "salescreate"

  patch 'sales/:id/update' => 'sales#update', as: "salesupdate"

  delete 'sales/:id/destroy' => 'sales#destroy', as: "salesdestroy"



  get 'markets/index' => 'markets#index', as: "marketsindex"

  get 'markets/show/:id' => 'markets#show', as: "marketsshow"

  get 'markets/:state/show' => 'markets#showstate', as: "marketsshowstate"

  get 'markets/:id/edit' => 'markets#edit', as: "marketsedit"

  get 'markets/new' => 'markets#new', as: "marketsnew"

  post 'markets/create' => 'markets#create', as: "marketscreate"

  patch 'markets/:id/update' => 'markets#update', as: "marketsupdate"

  delete 'markets/:id/destroy' => 'markets#destroy', as: "marketsdestroy"



  get 'vendors/index' => 'vendors#index', as: "vendorsindex"

  get 'vendors/new' => 'vendors#new', as: "vendorsnew"

  get 'vendors/show/:id' => 'vendors#show', as: "vendorsshow"

  get 'vendors/:id/edit' => 'vendors#edit', as: "vendorsedit"

  post 'vendors/create' => 'vendors#create', as: "vendorscreate"

  patch 'vendors/:id/update' => 'vendors#update', as: "vendorsupdate"

  delete 'vendors/:id/destroy' => 'vendors#destroy', as: "vendorsdestroy"

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :vendor
  has_many :sales
  has_many :markets

  validates :name, presence: true
  validates :vendor_id, presence: true, numericality: { only_integer: true }
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def findProduct
    return Product.find(params[:id].to_i)
  end

  def index
    @products = Product.all
  end

  def show
    @product = findProduct
  end

  def new
    @product = Product.new
  end

  def create
   @params = params
   @product = Product.new
   @product.name = params[:product][:name]
   @product.vendor_id = params[:product][:vendor_id]

   if(@product.save)
     #saved successfully; go to index
     redirect_to :action => "index"
   else
     #validation failed; show the "new" form again
     render :action => :new
   end
  end

  def edit
    @product = findProduct

    if @product == nil
          render :file => 'public/404.html',
              :status => :not_found
    end
  end

  def update
    @product = findProduct

    if @product == nil
          render :file => 'public/404.html',
              :status => :not_found
    end

    if @product.update(name: params[:product][:name], vendor_id: params[:product][:vendor_id])
      redirect_to action: "show"
    else
      render 'edit'
    end
  end

  def destroy
    @product = findProduct
    @product.destroy

    redirect_to action: "index"
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_productform.html.erb
<%= form_for @product,
  url: action_name do |f| %>
<ul>
  <li><%= f.label :name %></li>
  <li><%= f.text_field :name %></li>

  <li><%= f.label :vendor_id %></li>
  <li><%= f.select(:vendor_id, Vendor.all.map{|u| [u.name, u.id]}, {include_blank: true}) %></li>

  <li><%= f.submit class: 'button' %>
</ul>

  <% end %>

app/views/products/create.html.erb
<h1>Products#create</h1>
<p>Find me in app/views/products/create.html.erb</p>

app/views/products/destroy.html.erb
<h1>Products#destroy</h1>
<p>Find me in app/views/products/destroy.html.erb</p>

app/views/products/edit.html.erb
<h1>Edit a Product</h1>
<%= render partial: "productform", locals: { action_name: "update", params: {id: @product.id }} %>

app/views/products/index.html.erb
<h1>Here are all of the products!</h1>
<% @products.each do |product| %>

  <article>
    <h2><%= link_to(product.name, productsshow_path(product.id)) %></h2>
  </article>

<% end %>

app/views/products/new.html.erb
<h1>Add A New Product</h1>
<%= render partial: "productform", locals: { action_name: "create" } %>

app/views/products/show.html.erb
<h1><%= @product[:name] %></h1>

<article>
  <h3> Currently sold at:  </h3>
  <p>Market: <%= link_to(@product.vendor.market.name, marketsshow_path(@product.vendor.market.id)) %></p>
  <p>Vendor: <%= link_to(@product.vendor.name, marketsshow_path(@product.vendor.id)) %></p>

</article>

<ul class="align-buttons">
  <li><%= button_to 'Edit Product', productsedit_path(params[:id]), :class => "button", method: :get %></li>
  <li><%= button_to 'Delete Product', productsdestroy_path(params[:id]), :class => "button", method: :delete, data: {confirm: 'Are you sure?'} %>
  </li>
</ul>

app/views/products/update.html.erb
<h1>Products#update</h1>
<p>Find me in app/views/products/update.html.erb</p>